name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches: [ "main" ] # O cambia a "deploy" si vas a seguir la pauta estrictamente
    paths:
      - "frontend/**"

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Frontend y push a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPO_URL_FRONTEND }}
        # Cambiamos la versión fija por el ID del commit (SHA)
        IMAGE_TAG: ${{ github.sha }} 
      run: |
        cd frontend
        # Construimos con el ID único del commit
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # También le ponemos 'latest' para tener siempre una referencia fácil
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        # Subimos ambas etiquetas a ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Desplegar Frontend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar tienda-frontend con version SHA" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
            "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}",
            "docker stop tienda-frontend || true",
            "docker rm tienda-frontend || true",
            "docker run -d --name tienda-frontend -p 80:80 ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}"
          ]}' \
          --output text