name: CI/CD Tienda Perritos - Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1  

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      env:
        # Usamos el registro que sale del paso anterior + el nombre del repo
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # Asegúrate de que este secreto sea solo el NOMBRE del repo (ej: tienda-backend)
        ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME_BACKEND }} 
        IMAGE_TAG: ${{ github.sha }}
      run: |
        
        docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPO_URL_BACKEND }}:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/${{ secrets.ECR_REPO_URL_BACKEND }}:$IMAGE_TAG $ECR_REGISTRY/${{ secrets.ECR_REPO_URL_BACKEND }}:latest
        
        docker push $ECR_REGISTRY/${{ secrets.ECR_REPO_URL_BACKEND }}:$IMAGE_TAG
        docker push $ECR_REGISTRY/${{ secrets.ECR_REPO_URL_BACKEND }}:latest

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
            "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_URL_BACKEND }}:${{ github.sha }}",
            "docker stop tienda-backend || true",
            "docker rm tienda-backend || true",
            "docker run -d --name tienda-backend -p 3001:3001 ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_URL_BACKEND }}:${{ github.sha }}"
          ]}' \
          --output text